package base

import "errors"

var (
	ErrInvalidID           = errors.New("ridstore: invalid id")
	ErrNotFound            = errors.New("ridstore: not found")
	ErrLocked              = errors.New("ridstore: directory locked")
	ErrAlreadyExists       = errors.New("ridstore: store already exists")
	ErrNotInitialized      = errors.New("ridstore: store is not initialized")
	ErrInvalidConfig       = errors.New("ridstore: invalid configuration")
	ErrConfigMismatch      = errors.New("ridstore: configuration does not match store format")
	ErrClosed              = errors.New("ridstore: closed")
	ErrReadOnly            = errors.New("ridstore: read only after storage fault")
	ErrBatchClosed         = errors.New("ridstore: batch closed")
	ErrBatchFailed         = errors.New("ridstore: batch failed")
	ErrBatchTooLarge       = errors.New("ridstore: batch too large")
	ErrValueTooLarge       = errors.New("ridstore: value too large")
	ErrInvalidToken        = errors.New("ridstore: invalid version token")
	ErrConflict            = errors.New("ridstore: optimistic conflict")
	ErrIDExhausted         = errors.New("ridstore: id space exhausted")
	ErrAddressExhausted    = errors.New("ridstore: physical address space exhausted")
	ErrGenerationExhausted = errors.New("ridstore: metadata generation exhausted")
	ErrCommitUnknown       = errors.New("ridstore: commit outcome unknown")
	ErrStatusExpired       = errors.New("ridstore: batch status expired")
	ErrStatusCapacity      = errors.New("ridstore: batch status replay capacity reached")
	ErrCorrupt             = errors.New("ridstore: corruption detected")
	ErrUnsupported         = errors.New("ridstore: unsupported format")
	ErrInsufficientSpace   = errors.New("ridstore: insufficient free space")
	ErrRecoveryRequired    = errors.New("ridstore: recovery required before offline operation")
	ErrOverflow            = errors.New("ridstore: integer overflow")
	ErrInvalidAddress      = errors.New("ridstore: invalid physical address")
)
